### ISSUE TITLE
Message objects in `req.session.flash` do not clear up on refresh

### ISSUE THREAD

**Issue by serv** [expressjs/flash#1]
Alert message persists even on refreshing the browser because `req.session.flash` persists.
Is this by design?

How do I ensure that the flash gets cleared on any refresh?

**Comment by jonathanong** [comment]
you have to remove them yourself. it's just an array.

**Comment by serv** [comment]
I see. Just for future reference, I started doing this.

```js
app.get('/*', function(req,res,next) {
  req.session.flash = [];
  next();
});
```

So for every request, flash gets cleared.

**Comment by lewiswalsh** [comment]
@serv Your solution works, but I'm not sure how, can you explain?

**Comment by serv** [comment]
Sure, in express.js, `app.get('/*', function (req,res,next) { ... })` is a route method that runs prior to all the "get" calls. `*` is indicates the catch all routes. Read more about routes [here](http://expressjs.com/guide/routing.html).

Note that I placed that route method before all other "get" route methods.

**Comment by flexbrane** [comment]
@serv 
I put your code at the very end of my code, after all my routes. 
Now, all messages are sent one time and cleared just after that.

That's perfect, thanks!

**Comment by afalahi** [comment]
@serv hi, I realize this is 3 years ago, but I'm running into the same issue. I've tried pretty much everything I can think of, and I either get consistent messages, or no messages at all

**Comment by serv** [comment]
@afalahi Hey, it's been a while I used this package and I don't remember how I fixed the issue. Sorry about that.

**Comment by dpickett** [comment]
found it super weird that this middleware doesn't flush the session. I have this on the top of my routes:

```
app.use(flash())

// flush session
app.use((req, res, next) => {
  if (req.session && req.session.flash && req.session.flash.length > 0) {
    req.session.flash = []
  }
  next()
})
```

**Comment by mack-code0** [comment]
Would this not clear the flash session before it is used?

**Comment by sbminimalistics** [comment]
> Would this not clear the flash session before it is used?

That only clears session.flash, but by that time flash messages are already parsed into res.locals.flash

From the request life-time perspective it looks like that:
app.use(require("express-session")());
app.use(require("flash")());
...
app.use((req, res, next) => {
    req.session.flash = [];
    next();
})
...
app.get("/", function (req, res) {
    res.render("ejs_template", {
        // 'flash' property here is already set by require("flash")() above
    });
});

**Comment by Rohandeep7** [comment]
> @serv hi, I realize this is 3 years ago, but I'm running into the same issue. I've tried pretty much everything I can think of, and I either get consistent messages, or no messages at all

Hey, @afalahi found a solution yet?
